<?xml version="1.0"?>
<package format="3">
  <name>mower_description</name>
  <version>0.1.0</version>
  <description>Modelo URDF do robô cortador de grama (chassi 4 rodas skid-steer + LiDAR LD19)</description>
  <maintainer email="seu_email@exemplo.com">Seu Nome</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
